name: E2E Tests

on:
  push:
    branches: [main]
    paths: ["src/**", ".github/**", "docs/**", "tests/**"]
  pull_request:
  workflow_dispatch:

jobs:
  e2e-tests:
    name: Run E2E Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3 # @see https://stackoverflow.com/a/74885077/586823

      - name: Install dependencies
        run: pnpm i

      - name: Install sharp
        run: pnpm add sharp # @see https://github.com/withastro/astro/issues/9536#issuecomment-1880058215

      - name: Install Playwright Browsers
        run: pnpm run test:e2e:install

      - name: Run Playwright tests
        run: pnpm run test:e2e

      - uses: daun/playwright-report-summary@v2
        with:
          report-file: playwright-results.json
