name: Tests

on:
  push:
    branches: [main]
    paths: ["src/**", ".github/workflows/**", "website/**", "tests/**", "package.json"]
  pull_request:
    paths: ["src/**", ".github/workflows/**", "website/**", "tests/**", "package.json"]
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  tests:
    name: Run Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup PNPM first, so that we use the cache in the next action
      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm run test:unit

      - name: Require Build
        run: pnpm build

      - name: Install Playwright
        id: install-playwright
        uses: ./.github/actions/playwright

      - name: Debug Playwright Cache
        run: |
          echo "Playwright version – ${{ steps.install-playwright.outputs.version }}"
          echo "Playwright cached – ${{ steps.install-playwright.outputs.cache-hit }}"

      - name: Run Playwright tests
        run: pnpm run test:e2e

      - uses: daun/playwright-report-summary@v2
        with:
          report-file: playwright-results.json
